# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  rn: react-native-community/react-native@1.2.1

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  publish:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  publish:
    jobs:
      - checkout_code
      - publish:
          requires:
            - checkout_code
          filters:
            branches:
              only: master