# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  checkout_code:
    <<: *defaults  
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
        at: .
      - run:
        name: Install dependencies
        command: npm i 
  publish:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish to NPM
          command: npm run ci:publish

workflows:
  version: 1
  publish:
    jobs:
      - checkout_code
      - install_dependencies
      - publish:
          requires:
            - checkout_code
            - install_dependencies
          filters:
            branches:
              only: master