# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  checkout_code:
    <<: *defaults  
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .
  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v2-yarn-dependencies-{{ checksum "package.json" }}
            - v2-yarn-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-yarn-dependencies-{{ checksum "package.json" }}
          paths:
            - './node_modules'
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./node_modules/*
  publish:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: yarn ci:publish

workflows:
  version: 2
  publish:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - publish:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master