# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
